#include "../src/commands/char_mod.cpp"
#include "../src/commands/debug.cpp"
#include "../src/commands/info.cpp"
#include "../src/commands/map.cpp"
#include "../src/commands/moderation.cpp"
#include "../src/commands/server.cpp"
#include "../src/commands/warp.cpp"
