
/* $Id$
 * EOSERV is released under the zlib license.
 * See LICENSE.txt for more info.
 */

#include "../src/handlers/Account.cpp"
#include "../src/handlers/AdminInteract.cpp"
#include "../src/handlers/Attack.cpp"
#include "../src/handlers/Bank.cpp"
#include "../src/handlers/Barber.cpp"
#include "../src/handlers/Board.cpp"
#include "../src/handlers/Book.cpp"
#include "../src/handlers/Chair.cpp"
#include "../src/handlers/Character.cpp"
#include "../src/handlers/Chest.cpp"
#include "../src/handlers/Citizen.cpp"
#include "../src/handlers/Connection.cpp"
#include "../src/handlers/Door.cpp"
#include "../src/handlers/Emote.cpp"
#include "../src/handlers/Face.cpp"
#include "../src/handlers/Global.cpp"
#include "../src/handlers/Guild.cpp"
#include "../src/handlers/Init.cpp"
#include "../src/handlers/Internal.cpp"
#include "../src/handlers/Item.cpp"
#include "../src/handlers/Jukebox.cpp"
#include "../src/handlers/Locker.cpp"
#include "../src/handlers/Login.cpp"
#include "../src/handlers/Message.cpp"
#include "../src/handlers/Paperdoll.cpp"
#include "../src/handlers/Party.cpp"
#include "../src/handlers/Players.cpp"
#include "../src/handlers/Quest.cpp"
#include "../src/handlers/Refresh.cpp"
#include "../src/handlers/Shop.cpp"
#include "../src/handlers/Sit.cpp"
#include "../src/handlers/Spell.cpp"
#include "../src/handlers/StatSkill.cpp"
#include "../src/handlers/Talk.cpp"
#include "../src/handlers/Trade.cpp"
#include "../src/handlers/Walk.cpp"
#include "../src/handlers/Warp.cpp"
#include "../src/handlers/Welcome.cpp"
