
CFLAGS += -DEOSERV_MAKEFILE_LNX -DEOSERV_LINUX `mariadb_config --include`
CXXFLAGS += -std=gnu++0x -DEOSERV_MAKEFILE_LNX -DEOSERV_LINUX `mariadb_config --include`
LIBS += -lrt

MYSQL_LIB = `mariadb_config --libs`
SQLITE_LIB = -lsqlite3
PTHREAD_LIB = -lpthread

