/* fwd/guild.hpp
 * EOSERV is released under the zlib license.
 * See LICENSE.txt for more info.
 */

#ifndef FWD_GUILD_HPP_INCLUDED
#define FWD_GUILD_HPP_INCLUDED

class Guild_Member;
class Guild_Create;
class GuildManager;
class Guild;

enum GuildReply : short
{
	GUILD_BUSY = 1,
	GUILD_NOT_APPROVED = 2,
	GUILD_ALREADY_MEMBER = 3,
	GUILD_NO_CANDIDATES = 4,
	GUILD_EXISTS = 5,
	GUILD_CREATE_BEGIN = 6,
	GUILD_CREATE_ADD_CONFIRM = 7,
	GUILD_CREATE_ADD = 8,
	GUILD_RECRUITER_OFFLINE = 9,
	GUILD_RECRUITER_NOT_HERE = 10,
	GUILD_RECRUITER_WRONG_GUILD = 11,
	GUILD_NOT_RECRUITER = 12,
	GUILD_JOIN_REQUEST = 13,
	GUILD_NOT_PRESENT = 14,
	GUILD_ACCOUNT_LOW = 15,
	GUILD_ACCEPTED = 16,
	GUILD_NOT_FOUND = 17,
	GUILD_UPDATED = 18,
	GUILD_RANKS_UPDATED = 19,
	GUILD_REMOVE_LEADER = 20,
	GUILD_REMOVE_NOT_MEMBER = 21,
	GUILD_REMOVED = 22,
	GUILD_RANKING_LEADER = 23,
	GUILD_RANKING_NOT_MEMBER = 24
};

enum GuildInfoType : short
{
	GUILD_INFO_DESCRIPTION = 1,
	GUILD_INFO_RANKS = 2,
	GUILD_INFO_BANK = 3
};

#endif // FWD_GUILD_HPP_INCLUDED
