
/* $Id$
 * EOSERV is released under the zlib license.
 * See LICENSE.txt for more info.
 */

#ifndef EOCONST_HPP_INCLUDED
#define EOCONST_HPP_INCLUDED

// TODO: Remove this file

#include "fwd/character.hpp"
#include "fwd/eoclient.hpp"
#include "fwd/map.hpp"
#include "fwd/npc.hpp"
#include "fwd/party.hpp"
#include "fwd/player.hpp"
#include "fwd/world.hpp"

namespace eoconst
{

inline void ScriptRegister(ScriptEngine &engine)
{
	SCRIPT_REGISTER_ENUM("AdminLevel")
		SCRIPT_REGISTER_ENUM_VALUE(ADMIN_PLAYER);
		SCRIPT_REGISTER_ENUM_VALUE(ADMIN_GUIDE);
		SCRIPT_REGISTER_ENUM_VALUE(ADMIN_GUARDIAN);
		SCRIPT_REGISTER_ENUM_VALUE(ADMIN_GM);
		SCRIPT_REGISTER_ENUM_VALUE(ADMIN_HGM);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("Direction")
		SCRIPT_REGISTER_ENUM_VALUE(DIRECTION_DOWN);
		SCRIPT_REGISTER_ENUM_VALUE(DIRECTION_LEFT);
		SCRIPT_REGISTER_ENUM_VALUE(DIRECTION_UP);
		SCRIPT_REGISTER_ENUM_VALUE(DIRECTION_RIGHT);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("SitAction")
		SCRIPT_REGISTER_ENUM_VALUE(SIT_ACT_SIT);
		SCRIPT_REGISTER_ENUM_VALUE(SIT_ACT_STAND);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("Emote")
		SCRIPT_REGISTER_ENUM_VALUE(EMOTE_HAPPY);
		SCRIPT_REGISTER_ENUM_VALUE(EMOTE_DEPRESSED);
		SCRIPT_REGISTER_ENUM_VALUE(EMOTE_SAD);
		SCRIPT_REGISTER_ENUM_VALUE(EMOTE_ANGRY);
		SCRIPT_REGISTER_ENUM_VALUE(EMOTE_CONFUSED);
		SCRIPT_REGISTER_ENUM_VALUE(EMOTE_SURPRISED);
		SCRIPT_REGISTER_ENUM_VALUE(EMOTE_HEARTS);
		SCRIPT_REGISTER_ENUM_VALUE(EMOTE_MOON);
		SCRIPT_REGISTER_ENUM_VALUE(EMOTE_SUICIDAL);
		SCRIPT_REGISTER_ENUM_VALUE(EMOTE_EMBARASSED);
		SCRIPT_REGISTER_ENUM_VALUE(EMOTE_DRUNK);
		SCRIPT_REGISTER_ENUM_VALUE(EMOTE_TRADE);
		SCRIPT_REGISTER_ENUM_VALUE(EMOTE_LEVELUP);
		SCRIPT_REGISTER_ENUM_VALUE(EMOTE_PLAYFUL);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("QuestAction")
		SCRIPT_REGISTER_ENUM_VALUE(QUEST_PROGRESS);
		SCRIPT_REGISTER_ENUM_VALUE(QUEST_HISTORY);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("FileType")
		SCRIPT_REGISTER_ENUM_VALUE(FILE_MAP);
		SCRIPT_REGISTER_ENUM_VALUE(FILE_ITEM);
		SCRIPT_REGISTER_ENUM_VALUE(FILE_NPC);
		SCRIPT_REGISTER_ENUM_VALUE(FILE_SPELL);
		SCRIPT_REGISTER_ENUM_VALUE(FILE_CLASS);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("Gender")
		SCRIPT_REGISTER_ENUM_VALUE(GENDER_FEMALE);
		SCRIPT_REGISTER_ENUM_VALUE(GENDER_MALE);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("Skin")
		SCRIPT_REGISTER_ENUM_VALUE(SKIN_WHITE);
		SCRIPT_REGISTER_ENUM_VALUE(SKIN_YELLOW);
		SCRIPT_REGISTER_ENUM_VALUE(SKIN_TAN);
		SCRIPT_REGISTER_ENUM_VALUE(SKIN_ORC);
		SCRIPT_REGISTER_ENUM_VALUE(SKIN_SKELETON);
		SCRIPT_REGISTER_ENUM_VALUE(SKIN_PANDA);
		SCRIPT_REGISTER_ENUM_VALUE(SKIN_FISH);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("PaperdollIcon")
		SCRIPT_REGISTER_ENUM_VALUE(ICON_NORMAL);
		SCRIPT_REGISTER_ENUM_VALUE(ICON_GM);
		SCRIPT_REGISTER_ENUM_VALUE(ICON_HGM);
		SCRIPT_REGISTER_ENUM_VALUE(ICON_PARTY);
		SCRIPT_REGISTER_ENUM_VALUE(ICON_GM_PARTY);
		SCRIPT_REGISTER_ENUM_VALUE(ICON_HGM_PARTY);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("PartyRequestType")
		SCRIPT_REGISTER_ENUM_VALUE(PARTY_REQUEST_JOIN);
		SCRIPT_REGISTER_ENUM_VALUE(PARTY_REQUEST_INVITE);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("ClothesSlot")
		SCRIPT_REGISTER_ENUM_VALUE(SLOT_CLOTHES);
		SCRIPT_REGISTER_ENUM_VALUE(SLOT_HAIR);
		SCRIPT_REGISTER_ENUM_VALUE(SLOT_HAIRCOLOR);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("InitReply")
		SCRIPT_REGISTER_ENUM_VALUE(INIT_OUT_OF_DATE);
		SCRIPT_REGISTER_ENUM_VALUE(INIT_OK);
		SCRIPT_REGISTER_ENUM_VALUE(INIT_BANNED);
		SCRIPT_REGISTER_ENUM_VALUE(INIT_FILE_MAP);
		SCRIPT_REGISTER_ENUM_VALUE(INIT_FILE_EIF);
		SCRIPT_REGISTER_ENUM_VALUE(INIT_FILE_ENF);
		SCRIPT_REGISTER_ENUM_VALUE(INIT_FILE_ESF);
		SCRIPT_REGISTER_ENUM_VALUE(INIT_PLAYERS);
		SCRIPT_REGISTER_ENUM_VALUE(INIT_MAP_MUTATION);
		SCRIPT_REGISTER_ENUM_VALUE(INIT_FRIEND_LIST_PLAYERS);
		SCRIPT_REGISTER_ENUM_VALUE(INIT_FILE_ECF);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("InitBanType")
		SCRIPT_REGISTER_ENUM_VALUE(INIT_BAN_TEMP);
		SCRIPT_REGISTER_ENUM_VALUE(INIT_BAN_PERM);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("AccountReply")
		SCRIPT_REGISTER_ENUM_VALUE(ACCOUNT_EXISTS);
		SCRIPT_REGISTER_ENUM_VALUE(ACCOUNT_NOT_APPROVED);
		SCRIPT_REGISTER_ENUM_VALUE(ACCOUNT_CREATED);
		SCRIPT_REGISTER_ENUM_VALUE(ACCOUNT_CHANGE_FAILED);
		SCRIPT_REGISTER_ENUM_VALUE(ACCOUNT_CHANGED);
		SCRIPT_REGISTER_ENUM_VALUE(ACCOUNT_CONTINUE);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("CharacterReply")
		SCRIPT_REGISTER_ENUM_VALUE(CHARACTER_EXISTS);
		SCRIPT_REGISTER_ENUM_VALUE(CHARACTER_FULL);
		SCRIPT_REGISTER_ENUM_VALUE(CHARACTER_NOT_APPROVED);
		SCRIPT_REGISTER_ENUM_VALUE(CHARACTER_OK);
		SCRIPT_REGISTER_ENUM_VALUE(CHARACTER_DELETED);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("LoginReply")
		SCRIPT_REGISTER_ENUM_VALUE(LOGIN_WRONG_USER);
		SCRIPT_REGISTER_ENUM_VALUE(LOGIN_WRONG_USERPASS);
		SCRIPT_REGISTER_ENUM_VALUE(LOGIN_OK);
		SCRIPT_REGISTER_ENUM_VALUE(LOGIN_LOGGEDIN);
		SCRIPT_REGISTER_ENUM_VALUE(LOGIN_BUSY);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("WarpReply")
		SCRIPT_REGISTER_ENUM_VALUE(WARP_LOCAL);
		SCRIPT_REGISTER_ENUM_VALUE(WARP_SWITCH);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("TalkReply")
		SCRIPT_REGISTER_ENUM_VALUE(TALK_NOTFOUND);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("GuildReply")
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_BUSY);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_NOT_APPROVED);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_ALREADY_MEMBER);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_NO_CANDIDATES);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_EXISTS);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_CREATE_BEGIN);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_CREATE_ADD_CONFIRM);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_CREATE_ADD);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_RECRUITER_OFFLINE);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_RECRUITER_NOT_HERE);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_RECRUITER_WRONG_GUILD);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_NOT_RECRUITER);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_JOIN_REQUEST);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_NOT_PRESENT);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_ACCOUNT_LOW);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_ACCEPTED);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_NOT_FOUND);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_UPDATED);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_RANKS_UPDATED);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_REMOVE_LEADER);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_REMOVE_NOT_MEMBER);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_REMOVED);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_RANKING_LEADER);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_RANKING_NOT_MEMBER);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("GuildInfoType")
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_INFO_DESCRIPTION);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_INFO_RANKS);
		SCRIPT_REGISTER_ENUM_VALUE(GUILD_INFO_BANK);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("InnUnsubscribeReply")
		SCRIPT_REGISTER_ENUM_VALUE(UNSUBSCRIBE_NOT_CITIZEN);
		SCRIPT_REGISTER_ENUM_VALUE(UNSUBSCRIBE_UNSUBSCRIBED);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("SitState")
		SCRIPT_REGISTER_ENUM_VALUE(SIT_STAND);
		SCRIPT_REGISTER_ENUM_VALUE(SIT_CHAIR);
		SCRIPT_REGISTER_ENUM_VALUE(SIT_FLOOR);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("WarpAnimation")
		SCRIPT_REGISTER_ENUM_VALUE(WARP_ANIMATION_NONE);
		SCRIPT_REGISTER_ENUM_VALUE(WARP_ANIMATION_SCROLL);
		SCRIPT_REGISTER_ENUM_VALUE(WARP_ANIMATION_ADMIN);
		SCRIPT_REGISTER_ENUM_VALUE(WARP_ANIMATION_INVALID);
	SCRIPT_REGISTER_ENUM_END()

	SCRIPT_REGISTER_ENUM("MapEffect")
		SCRIPT_REGISTER_ENUM_VALUE(MAP_EFFECT_QUAKE);
	SCRIPT_REGISTER_ENUM_END()
}

}

#endif // EOCONST_HPP_INCLUDED
